<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="asep">

   <!-- Include macros -->
   <xacro:include filename="intertial.xacro"/>
   <xacro:include filename="camera.xacro" />

   <!-- Define properties -->
   <xacro:property name="length" value="0.5" />
   <xacro:property name="width" value="0.4" />
   <xacro:property name="height" value="0.3" />
   <xacro:property name="mass" value="10" />

   <!-- Links -->
   <link name="base_link" />

   <link name="chassis">
      <visual>
         <geometry>
            <box size="${length} ${width} ${height}" />
         </geometry>
      </visual>
      <collision>
         <geometry>
            <box size="${length} ${width} ${height}" />
         </geometry>
      </collision>
      <xacro:inertial mass="${mass}" x="${length}" y="${width}" z="${height}"/>
   </link>

   <joint name="base_link_chassis_joint" type="fixed">
      <parent link="base_link" />
      <child link="chassis" />
      <origin xyz="0 0 0" />
   </joint>

   <!-- CAMERA -->
   <xacro:camera parent_link="chassis">
      <origin xyz="${length / 2} 0 0" />
   </xacro:camera>

   <!-- Plugin Controller -->
   <gazebo>
      <plugin name="rov_controller" filename="librov_controller.so">
         <ros>
            <remapping>cmd_vel:=/cmd_vel</remapping>
            <remapping>camera:=/camera</remapping>
            <namespace>/</namespace>
            <parameter name="use_sim_time">true</parameter>
         </ros>
      </plugin>
   </gazebo>

</robot>
